### ISSUE TITLE
Selected Text and Background Colors

### ISSUE THREAD

**Issue by industrychanger** [bendemboski/DateSlider#18]
I'm still trying to figure out how this project works. I need to change the text colors within the ScrollLayout. Currently, the unselected text is a grey and the selected color is black. 

Where are these color values stored? How can they be change?
![image](https://f.cloud.github.com/assets/5972009/1845619/92d5da2c-7595-11e3-8ec0-b49e1f0c92d4.png)

**Comment by bendemboski** [comment]
Those values haven't really been pulled out and stored anywhere clean. You
can find them set from code in the various files here:
https://github.com/bendemboski/DateSlider/tree/develop/src/com/googlecode/android/widgets/DateSlider/timeview.
For example,
https://github.com/bendemboski/DateSlider/blob/develop/src/com/googlecode/android/widgets/DateSlider/timeview/TimeTextView.java#L42
 and
https://github.com/bendemboski/DateSlider/blob/develop/src/com/googlecode/android/widgets/DateSlider/timeview/TimeTextView.java#L82
