### ISSUE TITLE
DateSlider should accept a range of allowed times

### ISSUE THREAD

**Issue by bendemboski** [bendemboski/DateSlider#2]
The application should be able to optionally specify a start and/or end time that defines a (possibly half-open) range of allowable times. If the user tries to scroll back past the range start or forward past the range end, the scroller should just not scroll. This would be very useful for cases where the application needs the user to choose a time in the future, or in the past, and probably for other cases as well.

**Comment by danielberndt** [comment]
The DateSlider has a constructor containing  minDate and maxDate arguments. If they are not null, they will be considered as upper and/or lower limit
