### ISSUE TITLE
Incorrect @Override annotation on DateSlider.java

### ISSUE THREAD

**Issue by nickdaugherty** [bendemboski/DateSlider#8]
Iin DateSlider.java, line 138, the `run()` method is incorrectly annotated with `@Override`, which produces an error in Eclipse.

**Comment by bendemboski** [comment]
I think your eclipse must be mis-configured or something. That annotation is correct -- the class sub-classes Runnable, which you can see here definitely has a method with that signature:

http://developer.android.com/reference/java/lang/Runnable.html

**Comment by nickdaugherty** [comment]
`Runnable` is an interface, not a class, so you can't subclass (and override) it. The code creates a new Object that _implements_ `Runnable` rather than extends it, so there is nothing to `@Override`

**Comment by bendemboski** [comment]
Apologies for my sloppy language. You are correct that it is instantiating an `Object` that implements the `Runnable` interface. However, as of Java 1.6, you can use the `@Override` annotation on implementations of interface methods, and Android adheres to this standard. Perhaps you are switching between Java 1.5 and Java 1.6/Android projects, as described here:

http://stackoverflow.com/questions/3735661/bug-with-override-annotations-in-eclipse

**Comment by nickdaugherty** [comment]
Ah ha, yes this is the issue. Oddly my Eclipse global setting was JDK 1.7, but for that project it was set to 1.5. Thank you for your insight.
